clear; clc; close all;

% Unknown-scheduling experiment using the first Yu et al. benchmark plant
% and the DCPuls pipeline.  The true mu is generated by the hidden cosine
% law from the paper, while DCPuls receives only a candidate theta dictionary.
seedBase = 7;
rng(seedBase);

snr = 10;
n = 2;
p = 3;
N = 200;
Nmc = 100;
q = 3;                         % Observable theta dictionary dimension.

[A_cell, B_cell, C_cell] = plant();
data_vaf_clean = zeros(1, numel(snr));
data_nrmse_clean = zeros(1, numel(snr));
data_time_clean = zeros(1, numel(snr));
data_vaf_noisy = zeros(1, numel(snr));
data_nrmse_noisy = zeros(1, numel(snr));
data_time_noisy = zeros(1, numel(snr));
lastRun = struct('yTrue', [], 'yCleanEstimated', [], ...
    'yNoisyEstimated', [], 'snr', NaN);

for snrIndex = 1:numel(snr)
    snrDb = snr(snrIndex);
    vafCleanValues = zeros(1, Nmc);
    nrmseCleanValues = zeros(1, Nmc);
    timeCleanValues = zeros(1, Nmc);
    vafNoisyValues = zeros(1, Nmc);
    nrmseNoisyValues = zeros(1, Nmc);
    timeNoisyValues = zeros(1, Nmc);

    for mc = 1:Nmc
        fprintf('SNR = %g dB, run %d/%d\n', snrDb, mc, Nmc);
        u = randn(1, N);
        uValidation = randn(1, N);
        x0 = zeros(n, 1);
        muHidden = hidden_mu(N);

        [yClean, ~] = sim_lpv(A_cell, B_cell, C_cell, u, muHidden, x0);
        [yValidation, ~] = sim_lpv( ...
            A_cell, B_cell, C_cell, uValidation, muHidden, x0);

        noisePower = mean(yClean.^2) / 10^(snrDb / 10);
        validationNoisePower = mean(yValidation.^2) / 10^(snrDb / 10);
        yNoisy = yClean + sqrt(noisePower) * randn(size(yClean));
        yValidationNoisy = yValidation + sqrt(validationNoisePower) * ...
            randn(size(yValidation));

        thetaClean = make_theta(u, yClean);
        thetaValidationClean = make_theta(uValidation, yValidation);
        thetaNoisy = make_theta(u, yNoisy);
        thetaValidationNoisy = make_theta(uValidation, yValidationNoisy);

        [vafCleanValues(mc), nrmseCleanValues(mc), timeCleanValues(mc), ...
            yCleanEstimated] = fit_validate(u, yClean, thetaClean, ...
            uValidation, thetaValidationClean, yValidation, x0, n, p, q, 20);
        [vafNoisyValues(mc), nrmseNoisyValues(mc), timeNoisyValues(mc), ...
            yNoisyEstimated] = fit_validate(u, yNoisy, thetaNoisy, ...
            uValidation, thetaValidationNoisy, yValidation, x0, n, p, q, snrDb);
        fprintf(['Clean: VAF = %.2f%%, NRMSE = %.2f%%, time = %.3f s | ' ...
            'Noisy: VAF = %.2f%%, NRMSE = %.2f%%, time = %.3f s\n'], ...
            vafCleanValues(mc), nrmseCleanValues(mc), timeCleanValues(mc), ...
            vafNoisyValues(mc), nrmseNoisyValues(mc), timeNoisyValues(mc));

        if snrIndex == numel(snr) && mc == Nmc
            sampleCount = N - p;
            lastRun.yTrue = yValidation(1:sampleCount);
            lastRun.yCleanEstimated = yCleanEstimated;
            lastRun.yNoisyEstimated = yNoisyEstimated;
            lastRun.snr = snrDb;
        end
    end

    data_vaf_clean(snrIndex) = mean(vafCleanValues);
    data_nrmse_clean(snrIndex) = mean(nrmseCleanValues);
    data_time_clean(snrIndex) = mean(timeCleanValues);
    data_vaf_noisy(snrIndex) = mean(vafNoisyValues);
    data_nrmse_noisy(snrIndex) = mean(nrmseNoisyValues);
    data_time_noisy(snrIndex) = mean(timeNoisyValues);
    fprintf(['\nSNR = %g dB: clean VAF/NRMSE = %.2f%% / %.2f%%; ' ...
        'noisy VAF/NRMSE = %.2f%% / %.2f%%\n\n'], snrDb, ...
        data_vaf_clean(snrIndex), data_nrmse_clean(snrIndex), ...
        data_vaf_noisy(snrIndex), data_nrmse_noisy(snrIndex));
end

results = table(snr(:), data_vaf_clean(:), data_vaf_noisy(:), ...
    data_nrmse_clean(:), data_nrmse_noisy(:), data_time_clean(:), ...
    data_time_noisy(:), 'VariableNames', {'SNR_dB', 'CleanMeanVAF_percent', ...
    'NoisyMeanVAF_percent', 'CleanMeanNRMSE_percent', ...
    'NoisyMeanNRMSE_percent', 'CleanMeanTime_s', 'NoisyMeanTime_s'});
disp(results);
save('mu_unknown_dcpuls_results.mat', 'results');

if ~isempty(lastRun.yTrue)
    figure('Color', 'w', 'Name', 'Unknown-scheduling DCPuls output comparison', ...
        'Position', [160, 140, 960, 390]);
    plot(lastRun.yTrue, 'k-', 'LineWidth', 1.4); hold on;
    plot(lastRun.yCleanEstimated, 'b-', 'LineWidth', 1.35);
    plot(lastRun.yNoisyEstimated, 'r--', 'LineWidth', 1.5);
    grid on; box on;
    xlabel('Sample index'); ylabel('Output');
    title(sprintf('Validation output comparison at SNR = %g dB', lastRun.snr));
    legend({'True output', 'Noise-free identification', ...
        'Noisy identification (10 dB)'}, 'Location', 'best', 'Box', 'off');
    set(gca, 'FontName', 'Times New Roman', 'FontSize', 12);
end

function [vafValue, nrmseValue, elapsed, yEstimated] = fit_validate( ...
    u, yIdentification, thetaIdentification, uValidation, thetaValidation, ...
    yValidationClean, x0, n, p, q, snrDb)
identificationTimer = tic;
idOpts = struct('maxIterations', 20, 'tolerance', 1e-2, 'useParallel', true);
noiseScale = min(max(2 * 10^((20 - snrDb) / 6.05), 1e-3), 300);
idOpts.phiLagRidge = [0, 1e-2, 1e-1] * noiseScale;
[~, phiHat, idInfo] = idf_yu(u, yIdentification, thetaIdentification, p, n, 1, idOpts);
fprintf('idf_yu relative change = %.3e\n', idInfo.relativeChange);
hankelOpts = struct('iterations', 4, 'blend', 0.8, 'shiftWeight', 0.5);
phiReal = denoise_phi(phiHat, n, q, p, hankelOpts);
hoKalmanOpts = struct('shiftWeight', 0.5, 'rightRidgeFactor', 1e-2);
[Ahat, Bhat, Chat] = realize_phi(phiReal, n, q, p, hoKalmanOpts);
elapsed = toc(identificationTimer);

sampleCount = numel(uValidation) - p;
[yEstimated, ~] = sim_theta(Ahat, Bhat, Chat, ...
    uValidation(1:sampleCount), thetaValidation(:, 1:sampleCount), x0);
vafValue = calc_vaf(yValidationClean(1:sampleCount), yEstimated);
nrmseValue = calc_nrmse(yValidationClean(1:sampleCount), yEstimated);
end

function [A_cell, B_cell, C_cell] = plant()
A_data = [4/15, 1/15, 3/20, -1/60, 29/405, 2/81; ...
         -1/6, 1/30, -1/60, 3/20, 1/81, 52/405];
B_data = [1, 0.2, 0.2; 0, 0.2, -0.2];
C_data = [1, 0, 0, 0, 0, 0];
A_cell = {A_data(:, 1:2), A_data(:, 3:4), A_data(:, 5:6)};
B_cell = {B_data(:, 1), B_data(:, 2), B_data(:, 3)};
C_cell = {C_data(:, 1:2), C_data(:, 3:4), C_data(:, 5:6)};
end

function theta = make_theta(u, y)
theta = [ones(1, numel(u)); recip_cos(u); recip_cos(y)];
end

function value = recip_cos(signal)
% The paper uses cos(10/u) and cos(10/y).  The small floor prevents an
% undefined value at a zero input or initial output.
denominator = signal;
nearZero = abs(denominator) < 1e-3;
denominator(nearZero) = 1e-3 * sign(denominator(nearZero) + eps);
value = cos(10 ./ denominator);
end

function mu = hidden_mu(N)
k = 1:N;
mu = [ones(1, N); ...
    cos(8 * pi * k / N) / 2 + 0.2; ...
    cos(3.2 * pi * k / N + 0.5 * pi) / 3];
end

function [y, x] = sim_lpv(A_cell, B_cell, C_cell, u, mu, x0)
N = numel(u);
n = numel(x0);
x = zeros(n, N + 1);
y = zeros(1, N);
x(:, 1) = x0;
for k = 1:N
    A = zeros(n); B = zeros(n, 1); C = zeros(1, n);
    for basis = 1:size(mu, 1)
        A = A + mu(basis, k) * A_cell{basis};
        B = B + mu(basis, k) * B_cell{basis};
        C = C + mu(basis, k) * C_cell{basis};
    end
    y(k) = C * x(:, k);
    x(:, k + 1) = A * x(:, k) + B * u(k);
end
x = x(:, 1:end-1);
end

function [y, x] = sim_theta(A, B, C, u, theta, x0)
N = numel(u);
n = numel(x0);
x = zeros(n, N + 1);
y = zeros(1, N);
x(:, 1) = x0;
for k = 1:N
    y(k) = C * kron(theta(:, k), x(:, k));
    x(:, k + 1) = A * kron(theta(:, k), x(:, k)) + ...
        B * kron(theta(:, k), u(k));
end
x = x(:, 1:end-1);
end

function [phiOut, info] = denoise_phi(phi, n, r, p, opts)
if p < 3
    error('At least p = 3 is required for the generalized Hankel projection.');
end
nIter = get_opt(opts, 'iterations', 4);
blend = min(max(get_opt(opts, 'blend', 0.8), 0), 1);
weight = max(get_opt(opts, 'shiftWeight', 0.5), eps);
phiOut = phi(:);
rows = [words(r, 1), zeros(r, 1); words(r, 2)];
oneset = words(r, 1);
ratio = nan(1, nIter);
for iter = 1:nIter
    [H, Hs] = hankel_blocks(phiOut, rows, rows, oneset, r);
    Hj = H;
    for mode = 1:r
        Hj = [Hj, sqrt(weight) * Hs{mode}]; %#ok<AGROW>
    end
    [U, S, V] = svd(Hj, 'econ');
    sv = diag(S);
    if numel(sv) > n
        ratio(iter) = sv(n + 1) / max(sv(n), eps);
    end
    Hr = U(:, 1:n) * S(1:n, 1:n) * V(:, 1:n)';
    sums = zeros(size(phiOut));
    counts = zeros(size(phiOut));
    [sums, counts] = add_hankel(Hr(:, 1:size(H, 2)), rows, rows, ...
        sums, counts, r, []);
    for mode = 1:r
        first = size(H, 2) + (mode - 1) * size(oneset, 1) + 1;
        block = Hr(:, first:first + size(oneset, 1) - 1) / sqrt(weight);
        [sums, counts] = add_hankel(block, rows, oneset, ...
            sums, counts, r, mode);
    end
    projected = sums ./ max(counts, 1);
    phiOut = (1 - blend) * phiOut + blend * projected;
end
info = struct('iterations', nIter, 'blend', blend, 'shiftWeight', weight, ...
    'rankRatioHistory', ratio, ...
    'relativeCorrection', norm(phiOut - phi(:)) / max(norm(phi(:)), eps));
end

function [A, B, C, info] = realize_phi(phi, n, r, p, opts)
if p < 3
    error('At least p = 3 is required for this Ho-Kalman realization.');
end
rows = [words(r, 1), zeros(r, 1); words(r, 2)];
oneset = words(r, 1);
[H, Hs] = hankel_blocks(phi(:), rows, rows, oneset, r);
weight = max(get_opt(opts, 'shiftWeight', 0.5), eps);
Hj = H;
for mode = 1:r
    Hj = [Hj, sqrt(weight) * Hs{mode}]; %#ok<AGROW>
end
[U, S, V] = svd(Hj, 'econ');
sv = diag(S);
if numel(sv) < n || sv(n) <= eps(max(sv))
    error('Generalized Hankel matrix does not have numerical rank n.');
end
if numel(sv) > n
    rankRatio = sv(n + 1) / max(sv(n), eps);
else
    rankRatio = 0;
end
Obs = U(:, 1:n) * sqrt(S(1:n, 1:n));
Ctr = sqrt(S(1:n, 1:n)) * V(:, 1:n)';
R1 = Ctr(:, 1:r);
gram = R1 * R1';
noiseLevel = min(1, rankRatio / max(get_opt(opts, 'robustRankRatio', 2e-2), eps));
ridge = get_opt(opts, 'rightRidgeFactor', 0) * noiseLevel * trace(gram) / n;
C = reshape(Obs(1:r, :)', 1, []);
B = R1;
A = zeros(n, n * r);
shiftErr = zeros(r, 1);
for mode = 1:r
    first = size(H, 2) + (mode - 1) * r + 1;
    Rs = Ctr(:, first:first + r - 1) / sqrt(weight);
    if ridge > 0
        Am = Rs * R1' / (gram + ridge * eye(n));
    else
        Am = Rs / R1;
    end
    A(:, (mode - 1) * n + (1:n)) = Am;
    shiftErr(mode) = norm(Hs{mode} - Obs * Am * R1, 'fro') / ...
        max(norm(Hs{mode}, 'fro'), eps);
end
info = struct('singularValues', sv, 'rankRatio', rankRatio, ...
    'shiftResidual', shiftErr, 'hankel', H, 'jointHankel', Hj, ...
    'shiftWeight', weight, 'rightRidge', ridge, ...
    'noiseLevel', noiseLevel, 'rightCondition', cond(R1));
end

function [H, Hs] = hankel_blocks(phi, rows, cols, oneset, r)
H = zeros(size(rows, 1), size(cols, 1));
for i = 1:size(rows, 1)
    a = trim_word(rows(i, :));
    for j = 1:size(cols, 1)
        H(i, j) = phi(phi_index([a, trim_word(cols(j, :))], r));
    end
end
Hs = cell(1, r);
for mode = 1:r
    Hs{mode} = zeros(size(rows, 1), size(oneset, 1));
    for i = 1:size(rows, 1)
        a = trim_word(rows(i, :));
        for j = 1:size(oneset, 1)
            Hs{mode}(i, j) = phi(phi_index([a, mode, oneset(j, :)], r));
        end
    end
end
end

function [sums, counts] = add_hankel(block, rows, cols, sums, counts, r, mode)
for i = 1:size(block, 1)
    a = trim_word(rows(i, :));
    for j = 1:size(block, 2)
        b = trim_word(cols(j, :));
        if isempty(mode)
            word = [a, b];
        else
            word = [a, mode, b];
        end
        idx = phi_index(word, r);
        sums(idx) = sums(idx) + block(i, j);
        counts(idx) = counts(idx) + 1;
    end
end
end

function table = words(r, len)
table = zeros(r^len, len);
for row = 1:size(table, 1)
    value = row - 1;
    for col = len:-1:1
        table(row, col) = mod(value, r) + 1;
        value = floor(value / r);
    end
end
end

function word = trim_word(word)
word = word(word > 0);
end

function idx = phi_index(word, r)
len = numel(word);
if len < 2
    error('Predictor phi contains Markov words of length two or greater.');
end
idx = sum(r .^ (2:len - 1)) + 1;
for col = 1:len
    idx = idx + (word(col) - 1) * r^(len - col);
end
end

function value = get_opt(opts, name, defaultValue)
if isfield(opts, name) && ~isempty(opts.(name))
    value = opts.(name);
else
    value = defaultValue;
end
end

function value = calc_vaf(y, yhat)
value = max(0, 1 - var(y - yhat) / var(y)) * 100;
end

function value = calc_nrmse(y, yhat)
if ~isequal(size(y), size(yhat))
    error('y and yhat must have the same dimensions.');
end
y = y(:);
yhat = yhat(:);
value = 100 * norm(y - yhat) / norm(y - mean(y));
end
